### ISSUE TITLE
History List?

### ISSUE THREAD

**Issue by pajatopmr** [Ericgacoki/NeatFlix#15]
I just loaded up NeatFlix. Wow. It is awesome.
Is there a notion of history list? Or Continue Watching?
Two questions streaming video watchers ask repeatedly: 1) what network was that show on again? 2) what episode were we watching last?
I want to provide these two features, possibly adding to Neatflix if the features do not already exist.

Again, nicely done!

**Comment by Ericgacoki** [comment]
Since the app doesn't offer streaming services, it's not possible to keep a record as you mentioned. Maybe streaming will be available in the later versions.

Closing for now. Thanks!
