### ISSUE TITLE
Error in compilation

### ISSUE THREAD

**Issue by blackbirdsr71br** [Ericgacoki/NeatFlix#20]
Hi, I have an error went compiling the application, this the error

nable to find method ''org.jetbrains.kotlin.gradle.plugin.mpp.KotlinAndroidTarget org.jetbrains.kotlin.gradle.plugin.mpp.KotlinJvmAndroidCompilation.getTarget()''
'org.jetbrains.kotlin.gradle.plugin.mpp.KotlinAndroidTarget org.jetbrains.kotlin.gradle.plugin.mpp.KotlinJvmAndroidCompilation.getTarget()'

Gradle's dependency cache may be corrupt (this sometimes occurs after a network connection timeout.)

Re-download dependencies and sync project (requires network)
The state of a Gradle build process (daemon) may be corrupt. Stopping all Gradle daemons may solve this problem.

Stop Gradle build processes (requires restart)
Your project may be using a third-party plugin which is not compatible with the other plugins in the project or the version of Gradle requested by the project.

In the case of corrupt Gradle processes, you can also try closing the IDE and then killing all Java processes.

Thank's

**Comment by Ericgacoki** [comment]
Clearing the cache and restarting the IDE while connected to the internet should solve the problem.

**Comment by Ericgacoki** [comment]
Seems you were able to build the project. Please allow me to mark this as resolved.
